### ISSUE TITLE
Source FileNotFoundException

### ISSUE THREAD

**Issue by kacperduras** [FunnyGuilds/FunnyCreator#1]
```
[17:17:43.996][JavaFX Application Thread/INFO ] Creating primary view
[17:17:44.545][JavaFX Application Thread/INFO ] Showing view
[17:17:44.685][JavaFX Application Thread/INFO ] Injecting FGC bridge
[17:17:44.691][pool-2-thread-1/INFO ] Cloning FunnyGuilds repository
[17:17:50.869][pool-2-thread-1/INFO ] Repository has been cloned!
[17:17:50.870][pool-2-thread-1/INFO ] Building git repository
[17:17:50.874][pool-2-thread-1/INFO ] Hooked repository from 'funnyguilds-source'
[17:17:50.876][pool-2-thread-1/INFO ] Extracting maven
[17:17:55.454][pool-2-thread-1/INFO ] Parse pom.xml
[17:17:55.462][pool-2-thread-1/INFO ] Building repository
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building FunnyGuilds 4.0.0.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ funnyguilds ---
[INFO]
[INFO] --- git-commit-id-plugin:2.1.0:revision (default) @ funnyguilds ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ funnyguilds ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ funnyguilds ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 155 source files to C:\Users\WA\Desktop\creator\funnyguilds-source\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.450 s
[INFO] Finished at: 2017-10-15T17:18:00+02:00
[INFO] Final Memory: 13M/145M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project funnyguilds: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[17:18:00.322][pool-2-thread-1/INFO ] Something went wrong
[17:18:00.322][pool-2-thread-1/INFO ] Preparing output (FunnyGuilds 4.0.0.2)
java.io.FileNotFoundException: Source 'funnyguilds-source\target\funnyguilds-4.0.0.2.jar' does not exist
        at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1405)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1072)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1040)
        at net.dzikoysk.funnyguilds.creator.FunnyMaven.moveOutput(FunnyMaven.java:73)
        at net.dzikoysk.funnyguilds.creator.FunnyCreator.load(FunnyCreator.java:33)
        at net.dzikoysk.funnyguilds.creator.FunnyView.lambda$null$1(FunnyView.java:53)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by kacperduras** [comment]
```
[...] Perhaps you are running on a JRE rather than a JDK?
```

I just checked, versions are appropriate.

**Comment by dzikoysk** [comment]
`java -version`
